### ISSUE TITLE
CM12.1 Incompatible

### ISSUE THREAD

**Issue by npjohnson** [adt1-dev/android_device_google_molly#1]
When you try to use this to build CM12.1, it fails on libbtvendor.so and another wifi related library. I noticed you updated the Marvell driver for 5.0.x, are there any further changes you know would be necessary for 5.1.x?

**Comment by mknrls** [comment]
@npjohnson you would have to ask @C457. I dont know if he lost interest to continue this.
I created this organization repo like i had the adt-1 and wanted devs come help out do more development on this device. If you are interested or know other peoples that might be interested in contributing into to this repo i can add you to the organization.
