### ISSUE TITLE
Device Powercycles with network deadlock when HDMI is connected

### ISSUE THREAD

**Issue by abeatte** [adt1-dev/android_device_google_molly#3]
https://code.google.com/p/android-developer-preview/issues/detail?id=1879

**Comment by abeatte** [comment]
This is 100% reproducible on several ADT-1's. It occurs only when HDMI is connected.

**Comment by abeatte** [comment]
This issue is with stock ADT-1 firmware. I have not attempted to reproduce it with this CM based device tree.

**Comment by r3pwn** [comment]
I've never seen this issue before, even on stock. Try it on our CM before reporting it as an issue here, please.
